neo_switches:
  neo_ads_enabled:
    client: true
    default: false
  neo_ads_admin_only:
    client: true
    default: false
  neo_disable_ads_for_members:
    client: true
    default: true
  neo_house_disable_mobile_ads:
    client: true
    default: true
  neo_house_disable_desktop_ads:
    client: true
    default: true
  neo_house_debug:
    client: true
    default: true

neo_house:
  house_ads_after_nth_post:
    client: true
    default: 20
    min: 1
    max: 10000
  house_ads_frequency:
    client: true
    default: 100
    min: 0
    max: 100
  neo_house_through_trust_level:
    client: true
    default: 2
    enum: "TrustLevelSetting"

ad_plugin:
  no_ads_for_personal_messages:
    client: true
    default: true
  no_ads_for_restricted_categories:
    client: true
    default: false
  no_ads_for_groups:
    client: true
    default: ""
    type: group_list
  no_ads_for_categories:
    client: true
    default: ""
    type: category_list
  no_ads_for_tags:
    client: true
    default: ""
    type: list
  ads_txt:
    client: false
    default: ""
    textarea: true
